### ISSUE TITLE
StockPrediction_Transformer

### ISSUE THREAD

**Issue by tangxinglu** [makaveli10/StockPrediction_Transformer#1]
When run this code
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive
It appears:
ModuleNotFoundError: No module named 'termios'
![{%8A~59ZEIUT2~S71{HE1ZF](https://user-images.githubusercontent.com/66397266/112921831-0c94a480-913e-11eb-870f-2baa3d399261.png)

**Comment by makaveli10** [comment]
@tangxinglu Try this in [Google colaboratory](https://colab.research.google.com/). It'll work just fine.

- open colab
- import notebook from github
- change runtime type of colab notebook to gpu
