### ISSUE TITLE
recommended

### ISSUE THREAD

**Issue by microprediction** [makaveli10/StockPrediction_Transformer#2]
hi this was recommended to me by someone in the microprediction slack ([here btw](https://join.slack.com/t/microprediction/shared_invite/zt-xauc5r03-XmIMdy~iL4a3Hw3G1Agv6w)). Have you tried it out? Any interest in giving it a spin in the M6 competition?

**Comment by makaveli10** [comment]
@microprediction Hey, I havent tried it much for a very long time.
